export const siteConfig = {
  name: "Amsale Café",
  tagline: "Crafted with Ethiopian Tradition",
  address: { street: "4817 Walnut Street", city: "Philadelphia", state: "PA", zip: "19139" },
  phone: "(215) 397-4420",
  phoneTel: "+12153974420",
  email: "amsalecafe2022@gmail.com",
  hours: [
    { day: "Monday", value: "Closed", closed: true },
    { day: "Tuesday", value: "7:30 AM — 7:00 PM" },
    { day: "Wednesday", value: "7:30 AM — 7:00 PM" },
    { day: "Thursday", value: "7:30 AM — 7:00 PM" },
    { day: "Friday", value: "7:30 AM — 8:00 PM" },
    { day: "Saturday", value: "8:00 AM — 8:00 PM" },
    { day: "Sunday", value: "8:00 AM — 6:00 PM" },
  ],
  socials: {
    instagram: "https://instagram.com/amsalecafe",
    twitter: "https://twitter.com/amsalecafe",
    yelp: "https://www.yelp.com/biz/amsale-cafe-philadelphia",
  },
  mapsQuery: "https://maps.google.com/?q=4817+Walnut+Street+Philadelphia+PA+19139",
  mapsEmbed: "https://www.google.com/maps?q=4817+Walnut+Street+Philadelphia+PA+19139&output=embed",
  reviewLink: "https://search.google.com/local/writereview?placeid=ChIJamsaleCafePlaceholderID",
};

export const heroPhrases = [
  "Crafted with Ethiopian Tradition",
  "Fresh Coffee. Authentic Culture.",
  "A Modern Ethiopian Café Experience.",
  "Where Community Meets Coffee.",
];

export const menuCategories = [
  {
    id: "appetizers",
    label: "Appetizers",
    icon: "sambusa",
    blurb: "Small bites that begin the journey.",
    heroImage: "https://images.unsplash.com/photo-1601050690597-df0568f70950?crop=entropy&cs=srgb&fm=jpg&w=900&q=80",
    items: [
      { name: "Veggie Sambusa", amharic: "የአትክልት ሳምቡሳ", price: 3.00, description: "A delicate triangular pastry shell — folded by hand and shallow-fried until crisp — stuffed with whole brown lentils, sautéed onion, garlic, spinach, and just enough jalapeño to brighten each bite. A traditional starter from Ethiopian fasting days." },
      { name: "Meat Sambusa", amharic: "የሥጋ ሳምቡሳ", price: 3.50, description: "The same hand-folded pastry, this time filled with seasoned ground beef slow-cooked with onion, garlic, herbs and warming spices. Pan-fried to order and served hot — a beloved street-food classic of Addis Ababa." },
      { name: "Tematim Salad", amharic: "የቲማቲም ሳላድ", price: 8.50, description: "Vine-ripened tomatoes, sweet onion and jalapeño tossed with fresh garlic, lemon juice and olive oil — served over torn pieces of injera that soak up every drop of the bright, fragrant dressing." },
    ],
  },
  {
    id: "breakfast",
    label: "Breakfast",
    icon: "bowl",
    blurb: "Morning traditions to start your day.",
    heroImage: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?crop=entropy&cs=srgb&fm=jpg&w=900&q=80",
    items: [
      { name: "Kinche", amharic: "ቅንጬ", price: 9.50, description: "Cracked wheat slow-simmered with niter kibbeh (Ethiopian spiced clarified butter) until tender and creamy. The traditional Ethiopian porridge — wholesome, deeply nourishing, and the breakfast that fuels the highlands." },
      { name: "Firfir", amharic: "ፍርፍር", price: 9.50, description: "Pieces of injera bathed in a spicy lamb stew built on berbere, onion, garlic, and niter kibbeh. The bread soaks in the sauce until every torn piece carries the full weight of the spice. Comforting and bold." },
      { name: "Quanta Firfir", amharic: "ቋንጣ ፍርፍር", price: 12.50, description: "Quanta — air-dried, salted Ethiopian beef jerky — rehydrated in a peppery red sauce and folded into torn injera. Smoky, chewy, intensely savoury. A highland favorite." },
      { name: "Scrambled Eggs", amharic: "የእንቁላል ፍርፍር", price: 8.50, description: "Farm eggs scrambled gently with onion and jalapeño in spiced butter. Served with warm crusty bread or injera." },
      { name: "Full", amharic: "ፉል", price: 8.00, description: "Slow-stewed fava beans crushed at the table and topped with diced onion, fresh jalapeño, sour cream and tomato. A breakfast of the Horn of Africa eaten with warm bread — hearty, protein-rich, and built to start any day." },
    ],
  },
  {
    id: "entrees",
    label: "Entrées",
    icon: "utensils",
    blurb: "The heart of Ethiopian cuisine.",
    heroImage: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?crop=entropy&cs=srgb&fm=jpg&w=900&q=80",
    items: [
      { name: "Doro Qey Wot", amharic: "የዶሮ ቀይ ወጥ", price: 18.75, description: "The national dish of Ethiopia. Chicken simmered for hours in a deep red stew of berbere, slow-caramelized onion, garlic, ginger and niter kibbeh until the sauce thickens into velvet. Finished with a whole boiled egg. Best eaten by tearing injera with your right hand." },
      { name: "Kitfo", amharic: "ክትፎ", price: 18.75, description: "Hand-cut lean beef tartare seasoned with mitmita (a brilliant chili powder of bird's-eye, cardamom and cloves) and warm spiced butter. Served with homemade ayib (mild fresh cheese). Choose raw (lebleb), warmed-through (medium) or fully cooked." },
      { name: "Gored Gored", amharic: "ጐረድ ጐረድ", price: 17.50, description: "Cubes of lean beef tossed with awaze (a fiery chili paste), chopped onion, jalapeño and spiced butter. The bolder, chunkier cousin of kitfo. Choose raw, medium, or well done." },
      { name: "Tibs", amharic: "ጥብስ", price: 17.00, description: "Cubes of tender beef sautéed quickly over high heat with onion, garlic, jalapeño and olive oil. Served sizzling. The Ethiopian celebration dish — ordered at the start of every reunion." },
      { name: "Awaze Tibs", amharic: "አዋዜ ጥብስ", price: 17.50, description: "Tibs sautéed in awaze chili paste with onion and garlic — sharper, spicier, glossy with red oil." },
      { name: "Qey Wot", amharic: "የበሬ ሥጋ ቀይ ወጥ", price: 17.00, description: "Beef braised low and slow in a deep berbere stew with onion, garlic, spices and niter kibbeh until the meat falls apart and the sauce is dark and complex." },
      { name: "Yetibs Fitfit", amharic: "የጥብስ ፍትፍት", price: 16.50, description: "Beef tibs tossed with torn injera so the bread drinks up the sauce. Choose spicy or mild. A one-bowl meal with all the textures Ethiopian cooks love." },
      { name: "Yequanta Firfir", amharic: "የቋንጣ ፍርፍር", price: 16.50, description: "Air-dried beef cubes (quanta) simmered in red berbere sauce and folded with torn injera. Smoky, peppery, addictive." },
      { name: "Lamb Qey Wot", amharic: "የበግ ቀይ ወጥ", price: 17.50, description: "Lamb simmered in the classic red berbere stew with onion, garlic, spices and niter kibbeh until tender enough to scoop with injera alone." },
      { name: "Yebeg Tibs", amharic: "የበግ ጥብስ", price: 18.00, description: "Lamb cubes marinated with onion, tomato, garlic and green pepper, then quickly seared. Bright, herbaceous, less spicy than the awaze version." },
      { name: "Yebeg Awaze Tibs", amharic: "የበግ አዋዜ ጥብስ", price: 18.50, description: "Lamb marinated in red wine and sautéed with onion, garlic, berbere and niter kibbeh until glossy and intensely flavored." },
      { name: "Goden Tibs", amharic: "ጎድን ጥብስ", price: 18.50, description: "Prime short ribs sautéed with onion, tomato, fresh garlic and jalapeño. A house favorite — beefy, smoky, with the bone-in depth that makes Ethiopian short ribs unforgettable." },
      { name: "Beef Alcha", amharic: "አልጫ", price: 16.75, description: "The mild, golden side of Ethiopian cooking. Beef simmered with onion, garlic, turmeric, ginger and niter kibbeh — gentle, aromatic, perfect for those new to the cuisine." },
      { name: "Zilzil Tibs", amharic: "ዝልዝል ጥብስ", price: 16.50, description: "Long strips of beef seasoned with garlic, pepper, onion and a touch of rosemary. Served with two vegetable sides." },
      { name: "Gomen Besiga", amharic: "ጎመን በሥጋ", price: 13.00, description: "Seasoned beef braised with collard greens, onion and garlic. The Ethiopian answer to comfort food — earthy, nutritious, slow-cooked." },
    ],
  },
  {
    id: "vegetarian",
    label: "Vegetarian",
    icon: "leaf",
    blurb: "Plant-based tradition and flavor.",
    heroImage: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?crop=entropy&cs=srgb&fm=jpg&w=900&q=80",
    items: [
      { name: "Shiro Wot", amharic: "የሽሮ ወጥ", price: 12.50, description: "A thick, velvety stew made from finely ground chickpeas and split peas slow-simmered with berbere, caramelized onion, garlic and olive oil until silken. Topped with fresh jalapeño. The everyday Ethiopian comfort dish — vegan, deeply protein-rich, and built for scooping with injera." },
      { name: "Shiro Bedist", amharic: "ሽሮ በድስት", price: 14.00, description: "The same shiro but served bubbling hot in a traditional clay pot (dist) — the clay holds the heat and concentrates the aroma. The way it's meant to be eaten." },
      { name: "Veggie Combo · 4 Items", amharic: "", price: 16.50, description: "A sampler platter: misir wot (spiced red lentil stew), kik alicha (yellow split-pea stew), gomen (collard greens with garlic), and tikil gomen (cabbage with carrot and jalapeño). Served over a sheet of injera." },
      { name: "Veggie Combo · 5 Items", amharic: "", price: 17.50, description: "Adds shiro to the four-item combo — the full weekday Ethiopian table." },
      { name: "Veggie Combo · 7 Items", amharic: "", price: 18.50, description: "The feast. Shiro, spicy and mild lentil stews, yellow pea stew, collard greens, string beans with carrots, and cabbage — every flavor of the Ethiopian Orthodox fasting tradition on one platter." },
      { name: "Meat Combination", amharic: "የሥጋ በያይነቱ", price: 20.50, description: "A house sampler of qey wot, yebeg alcha fitfit, minchet abish, lamb qey wot and beef alcha — five preparations, two vegetable sides. The single best way to taste the range of Ethiopian cooking in one sitting." },
      { name: "Yebeg Alcha Fitfit", amharic: "የበግ አልጫ ፍትፍት", price: 17.50, description: "Lamb cooked in turmeric-golden alcha sauce with onion, garlic and niter kibbeh, then tossed with torn injera." },
    ],
  },
  {
    id: "beverages",
    label: "Beverages",
    icon: "cup",
    blurb: "Drinks that complete the ceremony.",
    heroImage: "https://images.unsplash.com/photo-1630861412757-d9743d318312?crop=entropy&cs=srgb&fm=jpg&w=900&q=80",
    items: [
      { name: "Coffee", amharic: "ቡና", price: 3.00, description: "Single-origin Ethiopian beans, freshly roasted in-house and brewed strong and aromatic. Coffee was first discovered here over 1,000 years ago — every cup is a thread back to that beginning." },
      { name: "Ethiopian Tea", amharic: "ሻይ", price: 1.99, description: "Black tea steeped with cardamom, clove and cinnamon — gently spiced and warming. The drink of long conversations." },
      { name: "Macchiato", amharic: "", price: 4.00, description: "Espresso 'marked' with velvety steamed milk — a small but mighty cup, a legacy of Italian influence in Eritrean and Ethiopian café culture." },
      { name: "Bottled Water", amharic: "", price: 1.50, description: "Still, cold, refreshing." },
      { name: "Pellegrino", amharic: "", price: 3.00, description: "Italian sparkling water." },
      { name: "Soda", amharic: "", price: 2.00, description: "Coke, Sprite, Ginger Ale and more." },
    ],
  },
];

export const reviewsData = [
  { name: "Selamawit M.", label: "Local Guide · Google Maps", stars: 5, text: "Absolutely the best Ethiopian food in Philadelphia. The doro wot tastes exactly like my mother's. Owner is incredibly welcoming and the injera is fresh every day. A West Philly treasure." },
  { name: "James R.", label: "Penn Grad Student · Google", stars: 5, text: "Stumbled in for coffee on a Tuesday and ended up coming back three more times that week. The kitfo is unreal — perfectly seasoned, generous portion. Coffee is honestly the cleanest pour I've had near campus." },
  { name: "Lily K.", label: "Drexel Faculty · Google", stars: 5, text: "Such a warm, beautifully decorated spot. The veggie combo is a steal and the owner walked us through every dish. Coffee ceremony on weekends is a must — bring time, it's slow on purpose." },
  { name: "Marcus D.", label: "Walnut Hill Resident · Google", stars: 5, text: "We've eaten here weekly for over a year. The tibs are consistently outstanding, the macchiato is perfect, and the staff knows us by name now. It feels like family." },
  { name: "Hanna A.", label: "Visitor from DC · Google", stars: 5, text: "I drove up from DC specifically because friends raved about it. Worth every mile. Quanta firfir was the best I've had outside Addis. The room is small, warm, and intentional — every detail considered." },
  { name: "Dr. Patrick W.", label: "CHOP Researcher · Google", stars: 5, text: "Quietly the most thoughtful café in University City. Sambusas are perfect for a 3 PM break, the Sidamo coffee is exceptional, and the wifi is steady. My second office." },
];

export const galleryImages = [
  { src: "https://images.unsplash.com/photo-1630861412757-d9743d318312?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Traditional Ethiopian coffee ceremony with cups and jebena pot" },
  { src: "https://images.unsplash.com/photo-1630861412229-67e2acb44b7a?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Ethiopian coffee ceremony close up" },
  { src: "https://images.pexels.com/photos/9409791/pexels-photo-9409791.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Warm hands holding a small ceramic cup of coffee" },
  { src: "https://images.pexels.com/photos/20825644/pexels-photo-20825644.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Roasted coffee beans on a brass tray" },
  { src: "https://images.unsplash.com/photo-1601065700897-d9fa1c093f3e?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Warm-lit café interior with wooden tables" },
  { src: "https://images.unsplash.com/photo-1550523303-e9e27624ed35?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Hands cradling a steaming espresso" },
  { src: "https://images.pexels.com/photos/3050828/pexels-photo-3050828.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Pour over coffee dripping into a glass server" },
  { src: "https://images.unsplash.com/photo-1575026469075-99e9e3433e72?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Hands wrapping around a warm latte" },
  { src: "https://images.pexels.com/photos/17486827/pexels-photo-17486827.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Coffee beans roasting over coals" },
  { src: "https://images.pexels.com/photos/17486836/pexels-photo-17486836.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Pouring coffee from the jebena" },
  { src: "https://images.unsplash.com/photo-1593252719532-53f183016149?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Ethiopian shared injera plate at dinner" },
  { src: "https://images.unsplash.com/photo-1729277133095-bff46b56c29a?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Pour over coffee inside a café" },
  { src: "https://images.unsplash.com/photo-1541469406036-71229832e06e?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Barista finishing a pour-over" },
  { src: "https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Two hands meeting around a small cup" },
  { src: "https://images.unsplash.com/photo-1728761390316-935ffeb3fbcc?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Cinematic café interior with golden window light" },
  { src: "https://images.unsplash.com/photo-1630861413071-a424a4d6d155?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Black ceramic jebena pot for coffee ceremony" },
];
