export const siteConfig = {
  name: "Amsale Café",
  tagline: "Crafted with Ethiopian Tradition",
  address: { street: "4817 Walnut Street", city: "Philadelphia", state: "PA", zip: "19139" },
  phone: "(215) 397-4420",
  phoneTel: "+12153974420",
  email: "amsalecafe2022@gmail.com",
  hours: [
    { day: "Monday", value: "Closed", closed: true },
    { day: "Tuesday", value: "7:30 AM — 7:00 PM" },
    { day: "Wednesday", value: "7:30 AM — 7:00 PM" },
    { day: "Thursday", value: "7:30 AM — 7:00 PM" },
    { day: "Friday", value: "7:30 AM — 8:00 PM" },
    { day: "Saturday", value: "8:00 AM — 8:00 PM" },
    { day: "Sunday", value: "8:00 AM — 6:00 PM" },
  ],
  socials: {
    instagram: "https://instagram.com/amsalecafe",
    twitter: "https://twitter.com/amsalecafe",
    yelp: "https://www.yelp.com/biz/amsale-cafe-philadelphia",
  },
  mapsQuery: "https://maps.google.com/?q=4817+Walnut+Street+Philadelphia+PA+19139",
  mapsEmbed: "https://www.google.com/maps?q=4817+Walnut+Street+Philadelphia+PA+19139&output=embed",
  reviewLink: "https://search.google.com/local/writereview?placeid=ChIJamsaleCafePlaceholderID",
};

export const heroPhrases = [
  "Crafted with Ethiopian Tradition",
  "Fresh Coffee. Authentic Culture.",
  "A Modern Ethiopian Café Experience.",
  "Where Community Meets Coffee.",
];

export const menuCategories = [
  {
    id: "appetizers",
    label: "Appetizers",
    icon: "sambusa",
    blurb: "Small bites that begin the journey.",
    items: [
      { name: "Veggie Sambusa", amharic: "የአትክልት ሳምቡሳ", price: 3.00, description: "Pastry shell filled with whole lentil, onions, spinach, and jalapeño." },
      { name: "Meat Sambusa", amharic: "የሥጋ ሳምቡሳ", price: 3.50, description: "Pastry shell filled with ground beef, onion, jalapeño, herbs and spices then pan fried and served hot." },
      { name: "Tematim Salad", amharic: "የቲማቲም ሳላድ", price: 8.50, description: "Fresh diced tomatoes, onion, jalapeño tossed with fresh garlic, lemon juice and olive oil with pieces of injera." },
    ],
  },
  {
    id: "breakfast",
    label: "Breakfast",
    icon: "bowl",
    blurb: "Morning traditions to start your day.",
    items: [
      { name: "Kinche", amharic: "ቅንጬ", price: 9.50, description: "Crushed wheat cooked to tender, seasoned with Ethiopian butter." },
      { name: "Firfir", amharic: "ፍርፍር", price: 9.50, description: "Hot spicy lamb stew tossed with injera." },
      { name: "Quanta Firfir", amharic: "ቋንጣ ፍርፍር", price: 12.50, description: "Beef jerky in stew tossed with injera." },
      { name: "Scrambled Eggs", amharic: "የእንቁላል ፍርፍር", price: 8.50, description: "Scrambled eggs with onion and jalapeño, served with fresh bread or injera." },
      { name: "Full", amharic: "ፉል", price: 8.00, description: "Crushed fava beans garnished with fresh onion, jalapeño, sour cream, and tomato; served with bread." },
    ],
  },
  {
    id: "entrees",
    label: "Entrées",
    icon: "utensils",
    blurb: "The heart of Ethiopian cuisine.",
    items: [
      { name: "Doro Qey Wot", amharic: "የዶሮ ቀይ ወጥ", price: 18.75, description: "Sautéed chicken in berbere-spiced sauce with onion, garlic, spices and butter, served with boiled egg." },
      { name: "Kitfo", amharic: "ክትፎ", price: 18.75, description: "Ground lean beef with mitmita, cardamom and special butter; served with homemade cheese. (Raw, medium, or well done.)" },
      { name: "Gored Gored", amharic: "ጐረድ ጐረድ", price: 17.50, description: "Cubes of lean beef with butter, awaze, chopped onion and jalapeño. (Raw, medium, or well done.)" },
      { name: "Tibs", amharic: "ጥብስ", price: 17.00, description: "Cubes of lean beef sautéed with onion, garlic, jalapeño and olive oil." },
      { name: "Awaze Tibs", amharic: "አዋዜ ጥብስ", price: 17.50, description: "Cubes of lean beef sautéed with awaze, onion, garlic and olive oil." },
      { name: "Qey Wot", amharic: "የበሬ ሥጋ ቀይ ወጥ", price: 17.00, description: "Beef cooked with onion, berbere, garlic, other spices and butter." },
      { name: "Yetibs Fitfit", amharic: "የጥብስ ፍትፍት", price: 16.50, description: "Cubes of beef in spicy or non-spicy sauce mixed with pieces of injera." },
      { name: "Yequanta Firfir", amharic: "የቋንጣ ፍርፍር", price: 16.50, description: "Air-dried beef cubes in special red sauce mixed with pieces of injera." },
      { name: "Lamb Qey Wot", amharic: "የበግ ቀይ ወጥ", price: 17.50, description: "Freshly chopped lamb with onion, berbere, garlic, spices and butter." },
      { name: "Yebeg Tibs", amharic: "የበግ ጥብስ", price: 18.00, description: "Cubes of lamb marinated with onion, tomato, garlic and green pepper." },
      { name: "Yebeg Awaze Tibs", amharic: "የበግ አዋዜ ጥብስ", price: 18.50, description: "Cubes of lamb marinated in red wine and sautéed with onion, garlic, berbere and butter." },
      { name: "Goden Tibs", amharic: "ጎድን ጥብስ", price: 18.50, description: "Prime short ribs sautéed with onion, tomato, fresh garlic and jalapeño." },
      { name: "Beef Alcha", amharic: "አልጫ", price: 16.75, description: "Beef cooked with onion, garlic, turmeric, spices and butter." },
      { name: "Zilzil Tibs", amharic: "ዝልዝል ጥብስ", price: 16.50, description: "Stripes of beef with garlic, pepper, onion and a touch of rosemary; served with two vegetable sides." },
      { name: "Gomen Besiga", amharic: "ጎመን በሥጋ", price: 13.00, description: "Seasoned beef cooked with collard greens, onion and garlic." },
    ],
  },
  {
    id: "vegetarian",
    label: "Vegetarian",
    icon: "leaf",
    blurb: "Plant-based tradition and flavor.",
    items: [
      { name: "Shiro Wot", amharic: "የሽሮ ወጥ", price: 12.50, description: "Powdered peas with onion, garlic and olive oil, topped with fresh jalapeño." },
      { name: "Shiro Bedist", amharic: "ሽሮ በድስት", price: 14.00, description: "Powdered peas with onion, garlic and olive oil, topped with jalapeño; served in a traditional clay pot." },
      { name: "Veggie Combo · 4 Items", amharic: "", price: 16.50, description: "Lentil stew, yellow pea stew, collard greens, and cabbage with jalapeño." },
      { name: "Veggie Combo · 5 Items", amharic: "", price: 17.50, description: "Shiro, lentil stew, yellow pea stew, collard greens, and cabbage with jalapeño." },
      { name: "Veggie Combo · 7 Items", amharic: "", price: 18.50, description: "Shiro, spicy and non-spicy lentil stews, yellow pea stew, collard greens, string beans & carrots, and cabbage." },
      { name: "Meat Combination", amharic: "የሥጋ በያይነቱ", price: 20.50, description: "Qey wot, yebeg alcha fitfit, minchet abish, lamb qey wot, beef alcha, plus two vegetable sides." },
      { name: "Yebeg Alcha Fitfit", amharic: "የበግ አልጫ ፍትፍት", price: 17.50, description: "Lamb cooked with onion, garlic, turmeric, spices and butter, mixed with pieces of injera." },
    ],
  },
  {
    id: "beverages",
    label: "Beverages",
    icon: "cup",
    blurb: "Drinks that complete the ceremony.",
    items: [
      { name: "Coffee", amharic: "ቡና", price: 3.00, description: "Fresh roasted, served hot and aromatic." },
      { name: "Ethiopian Tea", amharic: "ሻይ", price: 1.99, description: "Spiced and warming." },
      { name: "Macchiato", amharic: "", price: 4.00, description: "Bold espresso with velvety steamed milk." },
      { name: "Bottled Water", amharic: "", price: 1.50, description: "Still, cold, refreshing." },
      { name: "Pellegrino", amharic: "", price: 3.00, description: "Italian sparkling water." },
      { name: "Soda", amharic: "", price: 2.00, description: "Coke, Sprite, Ginger Ale and more." },
    ],
  },
];

export const reviewsData = [
  { name: "Selamawit M.", label: "Local Guide · Google Maps", stars: 5, text: "Absolutely the best Ethiopian food in Philadelphia. The doro wot tastes exactly like my mother's. Owner is incredibly welcoming and the injera is fresh every day. A West Philly treasure." },
  { name: "James R.", label: "Penn Grad Student · Google", stars: 5, text: "Stumbled in for coffee on a Tuesday and ended up coming back three more times that week. The kitfo is unreal — perfectly seasoned, generous portion. Coffee is honestly the cleanest pour I've had near campus." },
  { name: "Lily K.", label: "Drexel Faculty · Google", stars: 5, text: "Such a warm, beautifully decorated spot. The veggie combo is a steal and the owner walked us through every dish. Coffee ceremony on weekends is a must — bring time, it's slow on purpose." },
  { name: "Marcus D.", label: "Walnut Hill Resident · Google", stars: 5, text: "We've eaten here weekly for over a year. The tibs are consistently outstanding, the macchiato is perfect, and the staff knows us by name now. It feels like family." },
  { name: "Hanna A.", label: "Visitor from DC · Google", stars: 5, text: "I drove up from DC specifically because friends raved about it. Worth every mile. Quanta firfir was the best I've had outside Addis. The room is small, warm, and intentional — every detail considered." },
  { name: "Dr. Patrick W.", label: "CHOP Researcher · Google", stars: 5, text: "Quietly the most thoughtful café in University City. Sambusas are perfect for a 3 PM break, the Sidamo coffee is exceptional, and the wifi is steady. My second office." },
];

export const galleryImages = [
  { src: "https://images.unsplash.com/photo-1630861412757-d9743d318312?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Traditional Ethiopian coffee ceremony with cups and jebena pot" },
  { src: "https://images.unsplash.com/photo-1630861412229-67e2acb44b7a?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Ethiopian coffee ceremony close up" },
  { src: "https://images.pexels.com/photos/9409791/pexels-photo-9409791.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Warm hands holding a small ceramic cup of coffee" },
  { src: "https://images.pexels.com/photos/20825644/pexels-photo-20825644.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Roasted coffee beans on a brass tray" },
  { src: "https://images.unsplash.com/photo-1601065700897-d9fa1c093f3e?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Warm-lit café interior with wooden tables" },
  { src: "https://images.unsplash.com/photo-1550523303-e9e27624ed35?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Hands cradling a steaming espresso" },
  { src: "https://images.pexels.com/photos/3050828/pexels-photo-3050828.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Pour over coffee dripping into a glass server" },
  { src: "https://images.unsplash.com/photo-1575026469075-99e9e3433e72?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Hands wrapping around a warm latte" },
  { src: "https://images.pexels.com/photos/17486827/pexels-photo-17486827.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Coffee beans roasting over coals" },
  { src: "https://images.pexels.com/photos/17486836/pexels-photo-17486836.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=900", alt: "Pouring coffee from the jebena" },
  { src: "https://images.unsplash.com/photo-1593252719532-53f183016149?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Ethiopian shared injera plate at dinner" },
  { src: "https://images.unsplash.com/photo-1729277133095-bff46b56c29a?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Pour over coffee inside a café" },
  { src: "https://images.unsplash.com/photo-1541469406036-71229832e06e?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Barista finishing a pour-over" },
  { src: "https://images.unsplash.com/photo-1604881988758-f76ad2f7aac1?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Two hands meeting around a small cup" },
  { src: "https://images.unsplash.com/photo-1728761390316-935ffeb3fbcc?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Cinematic café interior with golden window light" },
  { src: "https://images.unsplash.com/photo-1630861413071-a424a4d6d155?crop=entropy&cs=srgb&fm=jpg&w=900&q=80", alt: "Black ceramic jebena pot for coffee ceremony" },
];
